<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{c21a987e-6403-4f80-aaa6-a55460efe5f1}" SpecialFunc="None">
    <Declaration><![CDATA[// Main Program Sweep (Cycle)
PROGRAM MAIN
VAR_TEMP 
  OB1_EV_CLASS : Byte;   // Bits 0-3 = 1 (Coming event), Bits 4-7 = 1 (Event class 1)
  OB1_SCAN_1 : Byte;   // 1 (Cold restart scan 1 of OB 1), 3 (Scan 2-n of OB 1)
  OB1_PRIORITY : Byte;   // Priority of OB Execution
  OB1_OB_NUMBR : Byte;   // 1 (Organization block 1, OB1)
  OB1_RESERVED_1 : Byte;   // Reserved for system
  OB1_RESERVED_2 : Byte;   // Reserved for system
  OB1_PREV_CYCLE : Int;   // Cycle time of previous OB1 scan (milliseconds)
  OB1_MIN_CYCLE : Int;   // Minimum cycle time of OB1 (milliseconds)
  OB1_MAX_CYCLE : Int;   // Maximum cycle time of OB1 (milliseconds)
  OB1_DATE_TIME : DATE_AND_TIME;   // Date and time OB1 started
END_VAR
VAR
  fbConvSys : FB_ConvSys;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbConvSys();

//just kidding around..:)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>